### ISSUE TITLE
Website mengarah ke situs terlarang

### ISSUE THREAD

**Issue by yahyaanwar** [sandhikagalih/project-kalian#14]
Pak @sandhikagalih senang sekali lihat streaming bapak, lalu tadi iseng aja pengen cari inspirasi dari project temen-temen WPU. Eh kok ada yang website yang nggak sopan (http://nunnaa.com/desa/). Duh.

Line of code:
https://github.com/sandhikagalih/project-kalian/blob/f487e8897602f666c1435ff0282a055297fd84b7/README.md?plain=1#L83
Website screenshot:
![image](https://user-images.githubusercontent.com/31283764/147769936-8baa05c4-655f-4918-b746-4af06d08ea45.png)

**Comment by sandhikagalih** [comment]
sudah diremove, terimakasih banyak 👍
